#ifndef POICA_PRIVATE_SUM_UNUSED_FIELD_TYPE
#define POICA_PRIVATE_SUM_UNUSED_FIELD_TYPE

typedef char POICA_P_SUM_UnusedFieldType;

#define POICA_P_SUM_UNUSED_VALUE ('\0')

#endif // POICA_PRIVATE_SUM_UNUSED_FIELD_TYPE
