name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install libdill
      run: wget http://libdill.org/libdill-2.14.tar.gz && tar -xzf libdill-2.14.tar.gz && cd libdill-2.14 && ./configure && make -j 4 && sudo make install
    - name: Build examples
      run: cd examples && mkdir build && cd build && cmake .. && cmake --build .

