name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost/Preprocessor
      run: sudo ./scripts/install_boost_pp.sh
    - name: Install libdill
      run: sudo ./scripts/install_libdill.sh
    - name: Build examples
      run: cd examples && mkdir build && cd build && cmake .. && cmake --build .
    - name: Run examples
      run: cd examples/build && ./ast && ./binary_tree && ./error_handling && ./heron_formula && ./message_passing && ./obj && ./tokens && ./product_introspection && ./sum_introspection
