name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Boost/Preprocessor
      run: sudo bash scripts/install_boost_pp.sh
    - name: Install libdill
      run: sudo bash scripts/install_libdill.sh
    - name: Build examples
      run: cd examples && mkdir build && cd build && cmake .. && cmake --build .
    - name: Run examples
      run: bash scripts/run_examples.sh
