name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Build examples
      run: cd examples && mkdir build && cd build && cmake .. && cmake --build .
    - name: Run examples
      run: bash scripts/run_examples.sh
